name: tag based on image version

on:
  push:
    branches:
      - main

jobs:

  tag:
    name: Create tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create tag on main if needed
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          VERSION="$(cat variables.tf | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')"
          if ! git rev-parse "$VERSION"; then
            git tag "$VERSION"
            git push --tags
          fi
